### ISSUE TITLE
BIt of a name clash

### ISSUE THREAD

**Issue by phillord** [jstamant/lilypond-mode#1]
I'm glad to see you working on this. There is a bit of a nameclash, though, as there is already a mode called lilypond mode bundled with lilypond.

**Comment by jstamant** [comment]
Yep. That's definitely a name clash. I swear I couldn't find a lilypond-mode when I made this. That's definitely my bad. I'll have to check out the one packaged with lilypond, for sure. But I'm already disliking how it's not available on any of the emacs package repositories. Kind of a pain to move around the `*.el` file.

Thanks for bringing this to my attention, @phillord

**Comment by phillord** [comment]
The other lilypond-mode is okay, but a bit broken, and could really do with some cleaning. And, yes, not being on in a package is poor.

There is a lot of room here for someone to do a better, more maintained job, I think.

**Comment by jstamant** [comment]
I'm busy with other projects of mine, but once I have time to commit to this, I'll most likely change the name of this mode. Hopefully I can make this a good mode in the future!
